export const ERROR_CONSTANTS = {
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export const API_ERRORS = {
  [ERROR_CONSTANTS.BAD_REQUEST]: {
    code: ERROR_CONSTANTS.BAD_REQUEST,
    statusCode: 400,
  },
  [ERROR_CONSTANTS.INVALID_CREDENTIALS]: {
    code: ERROR_CONSTANTS.INVALID_CREDENTIALS,
    statusCode: 401,
  },
  [ERROR_CONSTANTS.FORBIDDEN]: {
    code: ERROR_CONSTANTS.FORBIDDEN,
    statusCode: 403,
  },
  [ERROR_CONSTANTS.NOT_FOUND]: {
    code: ERROR_CONSTANTS.NOT_FOUND,
    statusCode: 404,
  },
  [ERROR_CONSTANTS.CONFLICT]: {
    code: ERROR_CONSTANTS.CONFLICT,
    statusCode: 409,
  },
  [ERROR_CONSTANTS.INTERNAL_ERROR]: {
    code: ERROR_CONSTANTS.INTERNAL_ERROR,
    statusCode: 500,
  },
};
